version: '3'

tasks:
  lint:
    cmds:
      - poetry run black --check .
      - poetry run mypy .

  fmt:
    cmds:
      - poetry run black .

  test:
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  create-usage-svg:
    cmds:
      - poetry run weather forecast "Potsdam DE" --export-svg usage.svg