version: '3'

tasks:
  lint:
    cmds:
      - poetry run black --check .
      - poetry run mypy .

  fmt:
    cmds:
      - poetry run black .

  test:
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  create-usage-svg:
    cmds:
      - poetry run weather forecast "Death Valley" --export-svg usage.svg
      - poetry run weather forecast "Death Valley" --export-svg usage-detailed.svg --resolution 3H